/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResearchChatRouteImport } from './routes/research-chat'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskExecutionIdRouteImport } from './routes/task-execution.$id'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchChatRoute = ResearchChatRouteImport.update({
  id: '/research-chat',
  path: '/research-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskExecutionIdRoute = TaskExecutionIdRouteImport.update({
  id: '/task-execution/$id',
  path: '/task-execution/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/mcp': typeof McpRoute
  '/office': typeof OfficeRoute
  '/pricing': typeof PricingRoute
  '/research-chat': typeof ResearchChatRoute
  '/reviews': typeof ReviewsRoute
  '/task-execution/$id': typeof TaskExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/mcp': typeof McpRoute
  '/office': typeof OfficeRoute
  '/pricing': typeof PricingRoute
  '/research-chat': typeof ResearchChatRoute
  '/reviews': typeof ReviewsRoute
  '/task-execution/$id': typeof TaskExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/mcp': typeof McpRoute
  '/office': typeof OfficeRoute
  '/pricing': typeof PricingRoute
  '/research-chat': typeof ResearchChatRoute
  '/reviews': typeof ReviewsRoute
  '/task-execution/$id': typeof TaskExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets'
    | '/mcp'
    | '/office'
    | '/pricing'
    | '/research-chat'
    | '/reviews'
    | '/task-execution/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasets'
    | '/mcp'
    | '/office'
    | '/pricing'
    | '/research-chat'
    | '/reviews'
    | '/task-execution/$id'
  id:
    | '__root__'
    | '/'
    | '/datasets'
    | '/mcp'
    | '/office'
    | '/pricing'
    | '/research-chat'
    | '/reviews'
    | '/task-execution/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsRoute: typeof DatasetsRoute
  McpRoute: typeof McpRoute
  OfficeRoute: typeof OfficeRoute
  PricingRoute: typeof PricingRoute
  ResearchChatRoute: typeof ResearchChatRoute
  ReviewsRoute: typeof ReviewsRoute
  TaskExecutionIdRoute: typeof TaskExecutionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-chat': {
      id: '/research-chat'
      path: '/research-chat'
      fullPath: '/research-chat'
      preLoaderRoute: typeof ResearchChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-execution/$id': {
      id: '/task-execution/$id'
      path: '/task-execution/$id'
      fullPath: '/task-execution/$id'
      preLoaderRoute: typeof TaskExecutionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsRoute: DatasetsRoute,
  McpRoute: McpRoute,
  OfficeRoute: OfficeRoute,
  PricingRoute: PricingRoute,
  ResearchChatRoute: ResearchChatRoute,
  ReviewsRoute: ReviewsRoute,
  TaskExecutionIdRoute: TaskExecutionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
